# Generated by Django 5.0.4 on 2024-04-18 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_quantity_product_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('publish_at',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
