# Generated by Django 5.0.4 on 2024-04-18 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('publish_at',), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
