# Generated by Django 4.2.11 on 2024-04-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(choices=[('a', 'New York'), ('b', 'Los Angles'), ('c', 'Texas'), ('d', 'San Francisco')], default='New York', max_length=255, verbose_name='City'),
        ),
    ]
